#@ load("/values.star", "values")
#@ load("/values.star", "resource")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset(resource("Deployment", "velero"))
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: velero
        env:
         #@overlay/match by="name"
         #@overlay/remove
         #@ if/end not values.backupStorageLocation.spec.provider == "aws" and not values.volumeSnapshotLocation.spec.provider == "aws":
        - name: AWS_SHARED_CREDENTIALS_FILE
        #@overlay/match by="name"
        #@overlay/remove
        #@ if/end not values.backupStorageLocation.spec.provider == "azure" and not values.volumeSnapshotLocation.spec.provider == "azure":
        - name: AZURE_CREDENTIALS_FILE
        args:
          #@ if values.restic.create and values.restic.defaultVolumesToRestic:
          #@overlay/append
          - --default-volumes-to-restic=true
          #@ end

          #@ if values.restic.create and values.restic.defaultResticPruneFrequency != 0:
          #@overlay/append
          - #@ "--default-restic-prune-frequency={}".format(values.restic.defaultResticPruneFrequency)
          #@ end
      initContainers:
      #@overlay/match by="name"
      #@overlay/remove
      #@ if/end not values.backupStorageLocation.spec.provider == "aws" and not values.volumeSnapshotLocation.spec.provider == "aws":
      - name: velero-plugin-for-aws
      #@overlay/match by="name"
      #@overlay/remove
      #@ if/end not values.backupStorageLocation.spec.provider == "azure" and not values.volumeSnapshotLocation.spec.provider == "azure":
      - name: velero-plugin-for-microsoft-azure
